import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React, { ReactNode } from "react";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProperties {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProperties) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen min-w-screen bg-background">
          <Sidebar />
          <div className="flex flex-col w-full h-full pr-12 pl-4">
            <Header />
            <div className="h-full w-full py-3">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
